services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: frontend-image:local
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8282:80"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: backend-image:local
    container_name: backend
    restart: unless-stopped
    environment:
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: database
      DB_PORT: ${POSTGRES_PORT}
      IP_ADDRESS_SERVER: ${IP_ADDRESS_SERVER}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres:10-alpine
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 2s
      timeout: 2s
      retries: 5

volumes:
  postgres_data:

   